
schemas:
  market_data: true
  convert_price_to_int: true
  portfolio_data: false

database:
  driver: sqlite3
  mkt_datat_dbpath: C:/Users/username/price_history.db
  portfolio_data_dbpath: C:/Users/username/portfolio_warehouse.db

security_types:
  - STK
  - ETF
  - CASH
  - FUT
  - OPT
  - IND
  - FOP
  - BOND
  - CMDTY
  - FUND
  - BAG
  - WAR
  - NEWS

seed_data:
  - SecTypes
  - Exchanges
  - FuturesContracts
  - FXPairs
  - Stocks
  - Options
  - Indeces
  - ETFs
  - Commodities
  - MutualFunds
  - Bonds
  - Warrents
  - NewsProviders

