name: CI - Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # or matrix if you prefer multiple versions

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          # Install your package dependencies if needed

      - name: Run pylint
        run: |
          # Adjust the path (e.g., `src/` or your package name) as appropriate
          pylint your_package_directory
